languageCode = "en-us"
title = "Rocker Science"
baseurl = "https://rocker.science/"

publishDir = "../docs"
ignoreFiles = [ "/keybase\\.txt$", "/CNAME$" ]

[params]
  linkedinProfileURL = "https://www.linkedin.com/in/paolo-serra/"
  keybaseProfileURL = "https://keybase.io/psychoweb/"
  lastfmProfileURL = "https://last.fm/user/psychoweb"
  lichessProfileURL = "https://en.lichess.org/@/bishek"

